/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica.uva.ipc.practica2.vista;

import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import practica.uva.ipc.practica2.modelo.Biblioteca;
import practica.uva.ipc.practica2.modelo.Libro;


/**
 * Esta clase es responsable de presentar los datos al usuario final y envia elementos al controlador
 * cuando se interactua con la interfaz grafica.
 * 
 * @author Sara Aparicio
 * @author Alejandra Gavino-Dias
 */
public class VistaBusqueda extends javax.swing.JFrame {
    
    private ControladorBusqueda controladorBusqueda;
    private Biblioteca modelo;
    
    /**
     * Crea una nueva VistaBusqueda.
     */
    public VistaBusqueda(Biblioteca modelo) {
        initComponents();
        this.modelo = modelo;
        this.controladorBusqueda = new ControladorBusqueda(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonOrdenarTitulo = new javax.swing.JButton();
        jButtonBusquedaTitulo = new javax.swing.JButton();
        jButtonBusquedaIsbn = new javax.swing.JButton();
        jButtonOrdenarPrecio = new javax.swing.JButton();
        jButtonEliminarFiltros = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLibros = new javax.swing.JList<>();
        jButtonEditarLibro = new javax.swing.JButton();
        jButtonGuardarFichero = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonCargarFichero = new javax.swing.JButton();
        jCheckSustituir = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelMensaje = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/practica/uva/ipc/practica2/imagenes/icono_biblioteca.png")));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Buscar por:");

        jTextFieldBusqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Buscar libro:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Ordenar por:");

        jButtonOrdenarTitulo.setBackground(new java.awt.Color(154, 198, 197));
        jButtonOrdenarTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonOrdenarTitulo.setText("Titulo");
        jButtonOrdenarTitulo.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonOrdenarTitulo.setMinimumSize(new java.awt.Dimension(69, 10));
        jButtonOrdenarTitulo.setPreferredSize(new java.awt.Dimension(69, 23));
        jButtonOrdenarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarTituloActionPerformed(evt);
            }
        });

        jButtonBusquedaTitulo.setBackground(new java.awt.Color(154, 198, 197));
        jButtonBusquedaTitulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonBusquedaTitulo.setText("Titulo");
        jButtonBusquedaTitulo.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonBusquedaTitulo.setMinimumSize(new java.awt.Dimension(69, 10));
        jButtonBusquedaTitulo.setPreferredSize(new java.awt.Dimension(69, 23));
        jButtonBusquedaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaTituloActionPerformed(evt);
            }
        });

        jButtonBusquedaIsbn.setBackground(new java.awt.Color(154, 198, 197));
        jButtonBusquedaIsbn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonBusquedaIsbn.setText("ISBN");
        jButtonBusquedaIsbn.setMaximumSize(new java.awt.Dimension(69, 23));
        jButtonBusquedaIsbn.setMinimumSize(new java.awt.Dimension(69, 10));
        jButtonBusquedaIsbn.setPreferredSize(new java.awt.Dimension(69, 23));
        jButtonBusquedaIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaIsbnActionPerformed(evt);
            }
        });

        jButtonOrdenarPrecio.setBackground(new java.awt.Color(154, 198, 197));
        jButtonOrdenarPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonOrdenarPrecio.setText("Precio");
        jButtonOrdenarPrecio.setMinimumSize(new java.awt.Dimension(69, 10));
        jButtonOrdenarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarPrecioActionPerformed(evt);
            }
        });

        jButtonEliminarFiltros.setText("Eliminar filtros");
        jButtonEliminarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonOrdenarPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonOrdenarTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonBusquedaTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonBusquedaIsbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(311, 311, 311))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldBusqueda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButtonEliminarFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrdenarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jButtonBusquedaIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOrdenarTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBusquedaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jListLibros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListLibros);

        jButtonEditarLibro.setBackground(new java.awt.Color(204, 204, 255));
        jButtonEditarLibro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonEditarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/uva/ipc/practica2/imagenes/icono_editar.png"))); // NOI18N
        jButtonEditarLibro.setText("EDITAR LIBRO");
        jButtonEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarLibroActionPerformed(evt);
            }
        });

        jButtonGuardarFichero.setBackground(new java.awt.Color(188, 210, 238));
        jButtonGuardarFichero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonGuardarFichero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/uva/ipc/practica2/imagenes/icono_cargar.png"))); // NOI18N
        jButtonGuardarFichero.setText("EXPORTAR LIBROS");
        jButtonGuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarFicheroActionPerformed(evt);
            }
        });

        jButtonMenu.setBackground(new java.awt.Color(204, 204, 255));
        jButtonMenu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/uva/ipc/practica2/imagenes/icono_menu.png"))); // NOI18N
        jButtonMenu.setText("IR A MENU");
        jButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMenuMouseExited(evt);
            }
        });
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jButtonCargarFichero.setBackground(new java.awt.Color(188, 210, 238));
        jButtonCargarFichero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCargarFichero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica/uva/ipc/practica2/imagenes/icono_descargar.png"))); // NOI18N
        jButtonCargarFichero.setText("IMPORTAR LIBROS");
        jButtonCargarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarFicheroActionPerformed(evt);
            }
        });

        jCheckSustituir.setText("Sustituir la biblioteca");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEditarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckSustituir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142))
                    .addComponent(jButtonCargarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarFichero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonGuardarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCargarFichero, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(jCheckSustituir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonEditarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 1, 62)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Búsqueda libros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelMensaje.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMensaje.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseEntered
        jButtonMenu.setBackground(new Color(51,204,255));
    }//GEN-LAST:event_jButtonMenuMouseEntered

    private void jButtonMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMenuMouseExited
        jButtonMenu.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_jButtonMenuMouseExited

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        controladorBusqueda.procesarVolverMenu();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonOrdenarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarPrecioActionPerformed
        jButtonOrdenarTitulo.setBackground(new Color(154,198,197));
        jButtonOrdenarPrecio.setBackground(new Color(51,204,255));
        controladorBusqueda.procesarOrdenarPrecio();
    }//GEN-LAST:event_jButtonOrdenarPrecioActionPerformed

    private void jButtonEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarLibroActionPerformed
        controladorBusqueda.procesarEditar(); 
    }//GEN-LAST:event_jButtonEditarLibroActionPerformed

    private void jButtonGuardarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarFicheroActionPerformed
        controladorBusqueda.procesarGenerarFichero();
    }//GEN-LAST:event_jButtonGuardarFicheroActionPerformed

    private void jButtonBusquedaIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaIsbnActionPerformed
        jButtonBusquedaTitulo.setBackground(new Color(154,198,197));
        jButtonBusquedaIsbn.setBackground(new Color(51,204,255));
        controladorBusqueda.procesarBusquedaIsbn();
    }//GEN-LAST:event_jButtonBusquedaIsbnActionPerformed

    private void jButtonBusquedaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaTituloActionPerformed
        jButtonBusquedaIsbn.setBackground(new Color(154,198,197));
        jButtonBusquedaTitulo.setBackground(new Color(51,204,255));
        controladorBusqueda.procesarBusquedaTitulo();
    }//GEN-LAST:event_jButtonBusquedaTituloActionPerformed

    private void jButtonOrdenarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarTituloActionPerformed
        jButtonOrdenarPrecio.setBackground(new Color(154,198,197));
        jButtonOrdenarTitulo.setBackground(new Color(51,204,255));
        controladorBusqueda.procesarOrdenarTitulo();
    }//GEN-LAST:event_jButtonOrdenarTituloActionPerformed
    
    private void jButtonCargarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarFicheroActionPerformed
        //este try catch lo ha generado solo el netbeans
        try {
            controladorBusqueda.procesarCargar();
        } catch (IOException ex) {
            Logger.getLogger(VistaBusqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCargarFicheroActionPerformed
    
    /**
     * Reinicia el estado de la vista tras eliminar los filtros.
     * @param evt 
     */
    private void jButtonEliminarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarFiltrosActionPerformed
        jButtonOrdenarPrecio.setBackground(new Color(154,198,197));
        jButtonOrdenarTitulo.setBackground(new Color(154,198,197));
        jButtonBusquedaIsbn.setBackground(new Color(154,198,197));
        jButtonBusquedaTitulo.setBackground(new Color(154,198,197));
        controladorBusqueda.eliminarFiltros();
        jTextFieldBusqueda.setText("");
    }//GEN-LAST:event_jButtonEliminarFiltrosActionPerformed

    /**
     * Devuelve el término de búsqueda del campo de búsqueda.
     * @return término de búsqueda
     */
    public String getTextoBusqueda(){
        return jTextFieldBusqueda.getText();
    }
    
    /**
     * Actualiza los libros del listado.
     * @param datos de los libros del listado
     */
    public void actualizarLista(String []datos) {
        jListLibros.setListData(datos);
    }
    
    /**
     * Devuelve los libros del listado como se muestra en la vista (no toda la biblioteca).
     * @return libros que se muestran en el listado
     */
    public ArrayList<String> getLista(){
        ArrayList<String> listaLibros=new ArrayList<String>();
        
        for (int i = 0; i < jListLibros.getModel().getSize(); i++) {
            Object item = jListLibros.getModel().getElementAt(i);
            listaLibros.add((String) item);  
        }
        while(listaLibros.remove(null)){}
        return listaLibros;
    }
    
    /**
     * Muestra en un label, los mensajes de error que puedan ocurrir.
     * @param mensaje de error
     */
    public void mostrarMensaje(String mensaje) {
        jLabelMensaje.setText(mensaje);
    }
    
    /**
     * Devuelve los datos del libro seleccionado en el listado de la vista.
     * @return cadena con los datos del libro seleccionado
     */
    public String libroSelecionado(){
        return jListLibros.getSelectedValue();
    }
    
    /**
     * Devuelve el valor del check box para sustituir la biblioteca al importar un fichero.
     * @return estado del check box
     */
    public boolean getValorSustituir(){
        return jCheckSustituir.isSelected();
    }
    
    /**
     * Establece el valor del check box para sustituir la biblioteca al importar un fichero.
     * @param estado boolean
     */
    public void setValorSustituir(boolean estado){
        jCheckSustituir.setSelected(estado);
    }
       
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBusquedaIsbn;
    private javax.swing.JButton jButtonBusquedaTitulo;
    private javax.swing.JButton jButtonCargarFichero;
    private javax.swing.JButton jButtonEditarLibro;
    private javax.swing.JButton jButtonEliminarFiltros;
    private javax.swing.JButton jButtonGuardarFichero;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonOrdenarPrecio;
    private javax.swing.JButton jButtonOrdenarTitulo;
    private javax.swing.JCheckBox jCheckSustituir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JList<String> jListLibros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
